### ISSUE TITLE
Design Project Framework

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/ProjectDocs#5]
# Project Framework

## Description
We must design framework for out project. It must show the outline of out project and should be well represented.

## Goal
To develop a framework best suited for out project.

## Tasks
- [ ] Design DFD for the system
- [ ] Design Database models and schemas
- [ ] Design System Architecture i.e how the system interact in api level
- [ ] Design System Flows
