### ISSUE TITLE
Proposal Introduction

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/ProjectDocs#6]
# Proposal Introduction

## Description
We need to briefly describe our Project.

## Tasks
- [ ] Research and Gather Details for the Project.
- [ ] List out the key points from the first task.
- [ ] Complete the Task
